api:
    type: rest
    prefix: /api
    resource: "@ApiBundle/Resources/config/routing.yml"

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

user_update:
    path:     /admin/user/save
    defaults: { _controller: AppBundle:Users:saveUser }
    methods:  [PUT]