api:
    type: rest
    prefix: /api
    resource: "@ApiBundle/Resources/config/routing.yml"

api_routing:
    resource: "@ApiBundle/Controller/"
    type:     annotation

api_pingdom:
    path:     /pingdom
    defaults: { _controller: ApiBundle:Tracking:check }
    methods:  [PUT, POST,GET]

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

user_update:
    path:     /admin/user/save
    defaults: { _controller: AppBundle:Users:saveUser }
    methods:  [PUT, POST]
