parameters:
      pingdom.checks_url: https://api.pingdom.com/api/2.0/checks
      pingdom.mail_pwd: bashmach@gmail.com:ww2UBhfZ
      pingdom.app_key: fg29h3mmnbbtqrhcgcxp00ra8sgrc02v

services:
     app_user.registration.form.type:
         class: AppBundle\Form\Type\RegistrationFormType
         arguments: [%fos_user.model.user.class%]
         tags:
             - { name: form.type, alias: app_user_registration }

     app.pingdom_connect:
         class: AppBundle\Util\PingdomConnection
         arguments: ["@service_container"]

     app.pingdom_status_add:
              class: AppBundle\Util\StatusRecord
              arguments: [ @doctrine.orm.entity_manager ]

     app.pingdom_websites_down:
         class: AppBundle\Util\WebsitesDown

     app.pingdom_send_alert:
         class: AppBundle\Util\SendAlert
         arguments: [@doctrine.orm.entity_manager, "@service_container"]

     app.send_alert_via_mail:
         class: AppBundle\Util\ViaMail
         arguments: [@doctrine.orm.entity_manager, "@service_container"]
