parameters:
      pingdom.checks_url: https://api.pingdom.com/api/2.0/checks
      pingdom.mail_pwd: bashmach@gmail.com:ww2UBhfZ
      pingdom.app_key: fg29h3mmnbbtqrhcgcxp00ra8sgrc02v
      send.alert.access.token: token1111

services:
     app_user.registration.form.type:
         class: AppBundle\Form\Type\RegistrationFormType
         arguments: [%fos_user.model.user.class%]
         tags:
             - { name: form.type, alias: app_user_registration }

     app.pingdom_get_checks:
         class: AppBundle\Util\GetChecks
         arguments: ["@service_container"]

     app.pingdom_delete_website:
              class: AppBundle\Util\DeleteSiteNotExistOnPingdom
              arguments: [@doctrine.orm.entity_manager]

     app.pingdom_websites_status:
         class: AppBundle\Util\WebsitesStatus

     app.pingdom_send_alert:
         class: AppBundle\Util\SendAlert
         arguments: [@doctrine.orm.entity_manager, "@service_container"]

     app.send_alert_via_mail:
         class: AppBundle\Util\ViaMail
         arguments: ["@service_container"]

     app.pingdom_create_new_check:
         class: AppBundle\Util\CreateCheck
         arguments: ["@service_container"]

     app.pingdom_delete_check:
         class: AppBundle\Util\DeleteCheck
         arguments: ["@service_container"]

     mail_task_consumer:
         class: AppBundle\Util\MailTaskConsumer
         arguments: ['@service_container', @doctrine.orm.entity_manager]

     app.pingdom_edit_check:
         class: AppBundle\Util\EditCheck
         arguments: ["@service_container"]

     app.pingdom_check_manipulate:
         class: AppBundle\Util\PrepareDataToManipulateCheck
         arguments: ["@service_container"]

#     post_persist_invite:
#          class: AppBundle\Listener\PostPersistInvite
#          arguments: ['@service_container']
#          tags:
#              - { name: doctrine.event_listener, event: postPersist, connection: default }