# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
      pingdom.checks_url: https://api.pingdom.com/api/2.0/checks
      pingdom.mail_pwd: bashmach@gmail.com:ww2UBhfZ
      pingdom.app_key: fg29h3mmnbbtqrhcgcxp00ra8sgrc02v

services:
     app_user.registration.form.type:
         class: AppBundle\Form\Type\RegistrationFormType
         arguments: [%fos_user.model.user.class%]
         tags:
             - { name: form.type, alias: app_user_registration }

     app.pingdom_connect:
         class: AppBundle\Util\PingdomConnection
         arguments: ["@service_container"]

     app.pingdom_status_add:
              class: AppBundle\Util\StatusRecord
              arguments: [ @doctrine.orm.entity_manager ]

#     services:
#         jms_serializer.object_constructor:
#             alias: jms_serializer.initialized_object_constructor
#             public: false
#         jms_serializer.initialized_object_constructor:
#              class:        VendorName\Bundle\ApiBundle\Services\InitializedObjectConstructor
#              arguments:    ["@jms_serializer.doctrine_object_constructor"]
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
