AppBundle\Entity\Websites:
    getters:
        name:
            - NotBlank:
        url:
            - NotBlank:
        status:
            - NotBlank:
AppBundle\Entity\Users:
     - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
        fields: phoneNumber
        properties:
              phoneNumber:
                  - NotBlank: ~
                  - PhoneNumber: ~
