AppBundle\Entity\Websites:
    getters:
        name:
            - NotBlank:
        url:
            - NotBlank:
        status:
            - NotBlank:

AppBundle\Entity\Users:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: phoneNumber
    properties:
        phoneNumber:
            - NotBlank: ~
#        groups: userValidation
#     - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
#        fields: phoneNumber
#        message: "My custom message"
#        groups: editValidation