AppBundle\Entity\Users:
    type: entity
    table: users
    uniqueConstraints:
        email_UNIQUE:
            columns:
                - email
        username_UNIQUE:
            columns:
                - username
        id_UNIQUE:
            columns:
                - id
        UNIQ_1483A5E992FC23A8:
            columns:
                - username_canonical
        UNIQ_1483A5E9A0D96FBF:
            columns:
                - email_canonical
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        username:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        password:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        salt:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        firstname:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: firstName
        lastname:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: lastName
        email:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        phonenumber:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
            column: phoneNumber
        created:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
        updated:
            type: datetime
            nullable: false
            options:
                default: '0000-00-00 00:00:00'
        enabled:
            type: boolean
            nullable: false
        roles:
            type: array
            nullable: false
            length: null
            options:
                fixed: false
        usernameCanonical:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: username_canonical
        emailCanonical:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: email_canonical
    lifecycleCallbacks: {  }
