AppBundle\Entity\Users:
    type: entity
    table: users
    uniqueConstraints:
        email_UNIQUE:
            columns:
                - email
        username_UNIQUE:
            columns:
                - username
        id_UNIQUE:
            columns:
                - id
        phoneNumber_UNIQUE:
            columns:
                - phoneNumber
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        firstName:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: firstName
        lastName:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: lastName
        phoneNumber:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
            column: phoneNumber
        created:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
        updated:
            type: datetime
            nullable: false
            options:
                default: '0000-00-00 00:00:00'
    lifecycleCallbacks: {  }
